

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  build-and-analyze:
    name: Build and Run Sonar analysis on JDK 17
    runs-on: ubuntu-latest

    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
        name: Checkout Code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo "Set up JDK 17"
        name: Set up JDK 17
      - uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'maven'

      # Cache Sonar packages which as used to run analysis and collect metrics
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - run: echo "Run Sonar"
        name: Run Sonar
      - run: mvn sonar:sonar -Dsonar.projectKey=exomiser-gregor -Dsonar.organization=exomiser-gregor -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # run quality checks with Qodana
      - name: Run Qodana
        uses: JetBrains/qodana-action@v2023.2
        env:
            QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      - name: Upload Qodana Results
        uses: actions/upload-artifact@v3
        with:
          name: qodana-results
          path: ${{ github.workspace }}/qodana-results
